# Generated by Django 5.1.6 on 2025-03-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
    ]
