# Generated by Django 5.1.6 on 2025-03-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20250302_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
